services:
  grafana:
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=${GRAFANA_ENVIRONMENT_GF_INSTALL_PLUGINS}
      - TZ=${TZ}
    restart: ${GRAFANA_RESTART}
    user: ${PUID}:${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_VOLUME_CONFIG}/grafana:/var/lib/grafana
      - ${DOCKER_VOLUME_STORAGE}:/storage
