---
services:
  prometheus:
    container_name: prometheus
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    restart: ${PROMETHEUS_RESTART}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_VOLUME_CONFIG}/prometheus:/config
      - ${DOCKER_VOLUME_STORAGE}:/storage
